// src/components/schedule/ScheduleLines.svelte
<script lang="ts">
  const times = [
    "07 am",
    "08 am",
    "09 am",
    "10 am",
    "11 am",
    "12 pm",
    "01 pm",
    "02 pm",
    "03 pm",
    "04 pm",
    "05 pm",
    "06 pm",
  ];
</script>

{#each times as time}
  <div class="flex flex-row items-center" aria-hidden="true">
    <p class="font-bold dark:text-stone-300">{time}</p>
    <div class="ml-5 h-0 grow border border-slate-900 dark:border-stone-300" />
  </div>
{/each}

// src/components/schedule/ScheduleLines.tsx
const ScheduleLines = () => {
  const times = [
    "07 am",
    "08 am",
    "09 am",
    "10 am",
    "11 am",
    "12 pm",
    "01 pm",
    "02 pm",
    "03 pm",
    "04 pm",
    "05 pm",
    "06 pm",
  ];
  return (
    <>
      {times.map((time) => (
        <div
          className="flex flex-row items-center"
          key={time}
          aria-hidden="true"
        >
          <p className="font-bold dark:text-stone-300">{time}</p>
          <div className="ml-5 h-0 grow border border-slate-900 dark:border-stone-300"></div>
        </div>
      ))}
    </>
  );
};

export default ScheduleLines;
