// src/components/schedule/TextChip.svelte
<script lang="ts">
  export let text: string;
  export let isSelected: boolean;
  export let onClick: () => void;

  let style: string;

  $: {
    style = `text-2xl font-black ${
      isSelected
        ? "text-slate-900 dark:text-white"
        : "text-slate-900/30 hover:scale-110"
    }`;
  }
</script>

<button on:click={onClick} class={style}>
  {text}
</button>

// src/components/TextChip.tsx
interface Props {
  text: string;
  isSelected: boolean;
  onClick: React.MouseEventHandler<HTMLParagraphElement>;
}

export default function TextChip({ text, isSelected, onClick }: Props) {
  return (
    <p
      onClick={onClick}
      className={`text-cairo text-2xl ${
        isSelected ? "text-black" : "text-black/20"
      } font-black`}
    >
      {text}
    </p>
  );
}
